server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: parking_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/parking-lots/**
        - id: vehicle_service
          uri: http://localhost:8083
          predicates:
            - Path=/api/vehicles/**
        - id: payment_service
          uri: http://localhost:8084
          predicates:
            - Path=/api/payments/**
